const data=[
    // slider 
    {
        "id": 1,
        "category":"SpecialDealsSlider",
        "title":"Fujiyoshida",
        "image":"https://getaway.qodeinteractive.com/wp-content/uploads/2017/08/tour-2-img-5-gallery.jpg",
        "price":"2500",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id": 2,
        "category":"SpecialDealsSlider",
        "title":"Piran",
        "image":"https://getaway.qodeinteractive.com/wp-content/uploads/2017/08/tour-2-img-6-gallery.jpg",
        "price":"1250",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id": 3,
        "category":"SpecialDealsSlider",
        "title":"Venice, Italy",
        "image":"	https://getaway.qodeinteractive.com/wp-content/uploads/2017/08/tour-2-img-7-gallery.jpg",
        "price":"350",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id": 4,
        "category":"SpecialDealsSlider",
        "title":"Dominican Republic",
        "image":"https://getaway.qodeinteractive.com/wp-content/uploads/2017/08/tour-2-img-8-gallery.jpg",
        "price":"1350",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id": 5,
        "category":"SpecialDealsSlider",
        "title":"Bari, Italy",
        "image":"	https://getaway.qodeinteractive.com/wp-content/uploads/2017/08/tour-2-img-9-gallery.jpg",
        "price":"850",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id": 6,
        "category":"SpecialDealsSlider",
        "title":"Bologna, Italy",
        "image":"https://getaway.qodeinteractive.com/wp-content/uploads/2017/08/tour-2-img-10-gallery.jpg",
        "price":"750",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id": 7,
        "category":"SpecialDealsSlider",
        "title":"Amsterdam",
        "image":"https://getaway.qodeinteractive.com/wp-content/uploads/2017/08/tour-2-img-11-gallery.jpg",
        "price":"750",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id": 8,
        "category":"SpecialDealsSlider",
        "title":"Seychelles",
        "image":"	https://getaway.qodeinteractive.com/wp-content/uploads/2017/08/tour-2-img-1-gallery.jpg",
        "price":"1250",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id": 9,
        "category":"SpecialDealsSlider",
        "title":"Arrecife, Spain",
        "image":"	https://getaway.qodeinteractive.com/wp-content/uploads/2017/08/tour-2-img-2-gallery.jpg",
        "price":"2200",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id": 10,
        "category":"SpecialDealsSlider",
        "title":"Tokyo, Japan",
        "image":"	https://getaway.qodeinteractive.com/wp-content/uploads/2017/08/tour-2-img-3-gallery.jpg",
        "price":"1950",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id": 11,
        "category":"SpecialDealsSlider",
        "title":"Krakow",
        "image":"	https://getaway.qodeinteractive.com/wp-content/uploads/2017/08/tour-2-img-4-gallery.jpg",
        "price":"250",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id":12,
        "title":"insta",
        "category":"Instagram",
        "image":"	https://scontent-bos5-1.cdninstagram.com/v/t51.288…oYfLGZVaj6UFtB39uoTJVxbWMKQGzgEXawn3A&oe=64A9F920",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id":13,
        "title":"insta",
        "image":"https://scontent-bos5-1.cdninstagram.com/v/t51.288…PXnB8M9civ3zeVWqxIKL8GWs6Ae-MepbuWRdw&oe=64AB40AB",
        "category":"Instagram",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id":14,
        "title":"insta",
        "image":"	https://scontent-bos5-1.cdninstagram.com/v/t51.288…UBRBFSs_oN8uqDFdAx_m_uStwwhIHl3m5T7Lw&oe=64AA323E",
        "category":"Instagram",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id":15,
        "title":"insta",
        "image":"https://scontent-bos5-1.cdninstagram.com/v/t51.288…hu91DjHhuVkcYsrIfoI69s_BPVSIrH7oxC5jw&oe=64AB5472",
        "category":"Instagram",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id":16,
        "title":"insta",
        "image":"	https://scontent-bos5-1.cdninstagram.com/v/t51.288…M-alDEnO-VhfxD7mgm6fnIN5hkf4XM3pI_VBw&oe=64AA9132",
        "category":"Instagram",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id":17,
        "title":"insta",
        "image":"	https://scontent-bos5-1.cdninstagram.com/v/t51.288…RllxHkXPNiOdVJr0wdFNDOID_wfTGW8SgPiug&oe=64AB6508",
        "category":"Instagram",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },

    // Logo 
    {
        "id":18,
        "title":"Logo",
        "image":"https://getaway.qodeinteractive.com/wp-content/uploads/2017/09/clients-1.png",
        "category":"logo",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id":19,
        "title":"Logo",
        "image":"https://getaway.qodeinteractive.com/wp-content/uploads/2017/09/clients-2.png",
        "category":"logo",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id":20,
        "title":"Logo",
        "image":"https://getaway.qodeinteractive.com/wp-content/uploads/2017/09/clients-3.png",
        "category":"logo",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id":21,
        "title":"Logo",
        "image":"https://getaway.qodeinteractive.com/wp-content/uploads/2017/09/clients-4.png",
        "category":"logo",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id":22,
        "title":"Logo",
        "image":"https://getaway.qodeinteractive.com/wp-content/uploads/2017/09/clients-5.png",
        "category":"logo",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id":23,
        "title":"Logo",
        "image":"https://getaway.qodeinteractive.com/wp-content/uploads/2017/09/clients-6.png",
        "category":"logo",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id":24,
        "title":"Logo",
        "image":"https://getaway.qodeinteractive.com/wp-content/uploads/2017/09/clients-7.png",
        "category":"logo",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id":25,
        "title":"Logo",
        "image":"https://getaway.qodeinteractive.com/wp-content/uploads/2017/09/clients-8.png",
        "category":"logo",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id":26,
        "title":"LogoClients",
        "image":"https://getaway.qodeinteractive.com/wp-content/upl…/2017/08/testimonials-background-img-2.jpg?id=990",
        "category":"logo",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id":27,
        "title":"LogoClients",
        "image":"https://getaway.qodeinteractive.com/wp-content/upl…/2017/08/testimonials-background-img-2.jpg?id=990",
        "category":"logo",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },

// h-img-gallery section
    {
        "id":28,
        "title":"h-img-gallery-1",
        "image":"https://getaway.qodeinteractive.com/wp-content/uploads/2017/08/h-img-gallery-1.jpg",
        "category":"img-gallery",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id":29,
        "title":"h-img-gallery-2",
        "image":"https://getaway.qodeinteractive.com/wp-content/uploads/2017/08/h-img-gallery-2.jpg",
        "category":"img-gallery",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id":30,
        "title":"h-img-gallery-3",
        "image":"https://getaway.qodeinteractive.com/wp-content/uploads/2017/08/h-img-gallery-3.jpg",
        "category":"img-gallery",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id":31,
        "title":"h-img-gallery-4",
        "image":"https://getaway.qodeinteractive.com/wp-content/uploads/2017/08/h-img-gallery-4.jpg",
        "category":"img-gallery",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id":32,
        "title":"h-img-gallery-5",
        "image":"https://getaway.qodeinteractive.com/wp-content/uploads/2017/08/h-img-gallery-5.jpg",
        "category":"img-gallery",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
    {
        "id":33,
        "title":"h-img-gallery-6",
        "image":"https://getaway.qodeinteractive.com/wp-content/uploads/2017/08/h-img-gallery-6.jpg",
        "category":"img-gallery",
        "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sollicitudin, tellus vitae… ",
    },
]
export default data;